# Generated by Django 5.0.14 on 2026-09-17 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="license_number",
        ),
        migrations.AddField(
            model_name="user",
            name="nmc_number",
            field=models.CharField(
                blank=True,
                help_text="Nepal Medical Council (NMC) License Number",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="specialization",
            field=models.CharField(
                blank=True,
                help_text="e.g. Orthodontist, Oral Surgeon, General Dentist",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="tenants.branch",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="tenants.clinic",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CLINIC_ADMIN", "Clinic Administrator"),
                    ("DENTIST", "Dentist / Specialist"),
                    ("RECEPTIONIST", "Receptionist"),
                ],
                default="RECEPTIONIST",
                max_length=20,
            ),
        ),
    ]
