# Generated by Django 6.1.1 on 2026-09-11 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="tenants.branch",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="tenants.clinic",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Administrator"),
                    ("CLINIC_ADMIN", "Clinic Administrator"),
                    ("DENTIST", "Dentist"),
                    ("DENTAL_ASSISTANT", "Dental Assistant"),
                    ("RECEPTIONIST", "Receptionist"),
                    ("ACCOUNTANT", "Accountant / Billing Staff"),
                ],
                default="RECEPTIONIST",
                max_length=30,
            ),
        ),
    ]
