# Generated by Django 5.0.14 on 2026-09-17 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        (
            "clinical",
            "0002_alter_toothrecord_options_remove_treatmentitem_notes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="treatment_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked treatment procedure if selected.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="charges",
                to="clinical.treatmentitem",
            ),
        ),
    ]
