# Generated by Django 5.0.14 on 2026-09-17 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Carestream Dental X-Ray / HD Intraoral Cam #1",
                        max_length=150,
                    ),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("XRAY", "X-Ray Machine"),
                            ("CAMERA", "Intraoral USB Camera"),
                            ("AUTOCLAVE", "Sterilization Autoclave"),
                            ("CHAIR", "Dental Chair Unit"),
                            ("SCALER", "Ultrasonic Scaler"),
                            ("OTHER", "Other Equipment"),
                        ],
                        default="XRAY",
                        max_length=30,
                    ),
                ),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "Operational"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("OUT_OF_SERVICE", "Out of Service"),
                        ],
                        default="OPERATIONAL",
                        max_length=30,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("last_service_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment",
                        to="tenants.branch",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="tenants.clinic",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
