# Generated by Django 5.0.14 on 2026-09-17 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encounters", "0002_remove_clinicalencounter_blood_pressure_and_more"),
        ("equipment", "0001_initial"),
        ("patients", "0002_rename_primary_branch_patient_branch_and_more"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientImaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imaging_type",
                    models.CharField(
                        choices=[
                            ("XRAY", "X-Ray Radiograph"),
                            ("INTRAORAL", "Intraoral Camera Photo"),
                            ("OPG", "OPG / Panoramic X-Ray"),
                            ("CBCT", "CBCT Scan"),
                            ("OTHER", "Other Clinical Image"),
                        ],
                        default="XRAY",
                        max_length=30,
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        help_text="Upload X-Ray or Intraoral Camera image file",
                        upload_to="patient_imaging/",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. Upper Left Molar Periapical X-Ray / #26 Cavity View",
                        max_length=150,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_images",
                        to="tenants.branch",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_images",
                        to="tenants.clinic",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imaging_records",
                        to="encounters.clinicalencounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imaging_records",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.DeleteModel(
            name="ClinicEquipment",
        ),
    ]
