# Generated by Django 5.0.14 on 2026-09-17 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("encounters", "0001_initial"),
        ("patients", "0002_rename_primary_branch_patient_branch_and_more"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        help_text="e.g. Flexon, Amoxyclav, Metrogyl", max_length=200
                    ),
                ),
                (
                    "generic_name",
                    models.CharField(
                        help_text="e.g. Ibuprofen + Paracetamol, Amoxicillin + Clavulanate",
                        max_length=200,
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("TABLET", "Tablet"),
                            ("CAPSULE", "Capsule"),
                            ("SYRUP", "Syrup"),
                            ("MOUTHWASH", "Mouthwash / Gargle"),
                            ("OINTMENT", "Ointment / Dental Gel"),
                            ("INJECTION", "Injection"),
                        ],
                        default="TABLET",
                        max_length=20,
                    ),
                ),
                (
                    "default_strength",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 500mg, 625mg, 0.2% w/v",
                        max_length=50,
                    ),
                ),
                (
                    "default_instructions",
                    models.TextField(
                        blank=True, help_text="Default dosage instructions."
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="tenants.clinic",
                    ),
                ),
            ],
            options={
                "ordering": ["brand_name"],
                "unique_together": {("clinic", "brand_name")},
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.CharField(blank=True, max_length=255)),
                (
                    "advice",
                    models.TextField(
                        blank=True,
                        help_text="General instructions: warm saline gargles, soft diet, avoid hot foods, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="tenants.branch",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="tenants.clinic",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="encounters.clinicalencounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "drug_name",
                    models.CharField(
                        help_text="Drug name if custom or selected from master.",
                        max_length=200,
                    ),
                ),
                (
                    "dosage",
                    models.CharField(help_text="e.g. 1 Tablet, 10ml", max_length=100),
                ),
                (
                    "frequency",
                    models.CharField(
                        help_text="e.g. 1-0-1 (Twice daily), 1-1-1 (Thrice daily)",
                        max_length=100,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        help_text="e.g. 5 Days, 7 Days, 2 Weeks", max_length=100
                    ),
                ),
                (
                    "timing",
                    models.CharField(
                        default="After meals",
                        help_text="e.g. After meals, Before bed",
                        max_length=100,
                    ),
                ),
                ("special_instructions", models.CharField(blank=True, max_length=255)),
                (
                    "medication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prescriptions.medication",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="prescriptions.prescription",
                    ),
                ),
            ],
        ),
    ]
