# Generated by Django 5.0.14 on 2026-09-17 12:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0002_rename_primary_branch_patient_branch_and_more"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. Complete RCT & Crown Plan", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft / Proposed"),
                            ("ACCEPTED", "Accepted by Patient"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatment_plans",
                        to="tenants.branch",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_plans",
                        to="tenants.clinic",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatment_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_plans",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TreatmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "procedure_name",
                    models.CharField(
                        help_text="e.g. Root Canal Treatment, Scaling, Composite Filling",
                        max_length=255,
                    ),
                ),
                (
                    "tooth_number",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="FDI Tooth Number (Optional)", null=True
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost in NPR",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "treatment_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="clinical.treatmentplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToothRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tooth_number",
                    models.PositiveSmallIntegerField(
                        help_text="FDI Tooth Number (11-48)"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("SOUND", "Sound / Healthy"),
                            ("CARIES", "Dental Caries / Decay"),
                            ("RESTORED", "Restored / Filled"),
                            ("ROOT_CANAL", "Root Canal Treated (RCT)"),
                            ("CROWN", "Crown / Cap"),
                            ("MISSING", "Missing / Extracted"),
                        ],
                        default="SOUND",
                        max_length=20,
                    ),
                ),
                (
                    "surface",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Occlusal, Mesial, Distal, Buccal, Lingual",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tooth_records",
                        to="tenants.clinic",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tooth_records",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["tooth_number"],
                "unique_together": {("patient", "tooth_number")},
            },
        ),
    ]
