# Generated by Django 5.0.14 on 2026-09-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="toothrecord",
            options={},
        ),
        migrations.RemoveField(
            model_name="treatmentitem",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="treatmentitem",
            name="status",
        ),
        migrations.RemoveField(
            model_name="treatmentplan",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="treatmentitem",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="toothrecord",
            name="condition",
            field=models.CharField(
                choices=[
                    ("SOUND", "Sound"),
                    ("CARIES", "Dental Caries"),
                    ("MISSING", "Missing Tooth"),
                    ("FILLED", "Filled / Restored"),
                    ("RCT", "Root Canal Treated"),
                    ("CROWN", "Crown / Cap"),
                    ("BRIDGE", "Bridge"),
                    ("IMPLANT", "Dental Implant"),
                ],
                default="SOUND",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="toothrecord",
            name="surface",
            field=models.CharField(
                blank=True, help_text="e.g. Occlusal, Mesial, Distal", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="toothrecord",
            name="tooth_number",
            field=models.PositiveIntegerField(help_text="FDI tooth notation: 11-48"),
        ),
        migrations.AlterField(
            model_name="treatmentitem",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, help_text="Cost in NPR", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="treatmentitem",
            name="procedure_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="treatmentitem",
            name="tooth_number",
            field=models.PositiveIntegerField(
                blank=True, help_text="FDI Tooth # if applicable", null=True
            ),
        ),
        migrations.AlterField(
            model_name="treatmentplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PLANNED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="treatmentplan",
            name="title",
            field=models.CharField(
                help_text="e.g. Full Mouth Rehabilitation, Orthodontic Plan",
                max_length=255,
            ),
        ),
    ]
