# Generated by Django 5.0.14 on 2026-09-17 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("patients", "0002_rename_primary_branch_patient_branch_and_more"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalEncounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encounter_date", models.DateTimeField(auto_now_add=True)),
                (
                    "blood_pressure",
                    models.CharField(
                        blank=True, help_text="e.g., 120/80 mmHg", max_length=20
                    ),
                ),
                (
                    "pulse_rate",
                    models.PositiveIntegerField(blank=True, help_text="bpm", null=True),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="°F",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(
                        help_text="Primary reason for visit in patient's words."
                    ),
                ),
                ("history_of_present_illness", models.TextField(blank=True)),
                (
                    "examination_notes",
                    models.TextField(
                        blank=True,
                        help_text="Clinical findings during oral examination.",
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(
                        blank=True, help_text="Provisional or definitive diagnosis."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounter",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters",
                        to="tenants.branch",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="tenants.clinic",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-encounter_date"],
            },
        ),
    ]
