# Generated by Django 5.0.14 on 2026-09-17 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("encounters", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinicalencounter",
            name="blood_pressure",
        ),
        migrations.RemoveField(
            model_name="clinicalencounter",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="clinicalencounter",
            name="examination_notes",
        ),
        migrations.RemoveField(
            model_name="clinicalencounter",
            name="history_of_present_illness",
        ),
        migrations.RemoveField(
            model_name="clinicalencounter",
            name="pulse_rate",
        ),
        migrations.RemoveField(
            model_name="clinicalencounter",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="clinicalencounter",
            name="bp",
            field=models.CharField(
                blank=True, help_text="Blood Pressure e.g. 120/80", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="clinicalencounter",
            name="clinical_findings",
            field=models.TextField(
                default=1, help_text="Objective: Examination & clinical findings"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicalencounter",
            name="pulse",
            field=models.CharField(
                blank=True, help_text="Pulse rate bpm", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="clinicalencounter",
            name="tooth_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional FDI Tooth # involved in this visit (11-48)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clinicalencounter",
            name="treatment_notes",
            field=models.TextField(
                blank=True, help_text="Plan: Treatment executed or advised"
            ),
        ),
        migrations.AlterField(
            model_name="clinicalencounter",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="encounters",
                to="appointments.appointment",
            ),
        ),
        migrations.AlterField(
            model_name="clinicalencounter",
            name="chief_complaint",
            field=models.TextField(help_text="Subjective: Patient's chief complaint"),
        ),
        migrations.AlterField(
            model_name="clinicalencounter",
            name="diagnosis",
            field=models.CharField(
                blank=True, help_text="Assessment / Diagnosis", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="clinicalencounter",
            name="temperature",
            field=models.CharField(
                blank=True, default=1, help_text="Temperature", max_length=20
            ),
            preserve_default=False,
        ),
    ]
