# Generated by Django 6.1.1 on 2026-09-11 13:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("patient_code", models.CharField(db_index=True, max_length=50)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=50)),
                (
                    "alternate_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "emergancy_contact_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "emergancy_contact_phone",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                (
                    "allergies",
                    models.TextField(
                        blank=True,
                        help_text="Known drug or environmental allergies",
                        null=True,
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(
                        blank=True,
                        help_text="Pre-existing medical conditions",
                        null=True,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.clinic"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("clinic", "patient_code")},
            },
        ),
    ]
