# Generated by Django 5.0.14 on 2026-09-16 16:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(
                        help_text="Unique patient ID formatted per clinic scope e.g., P-00101",
                        max_length=50,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        default="MALE",
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("alternate_phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "allergies",
                    models.TextField(
                        blank=True,
                        help_text="Known drug/substance allergies (e.g., Penicillin, Amoxicillin, Latex)",
                    ),
                ),
                (
                    "medical_history",
                    models.TextField(
                        blank=True,
                        help_text="Medical conditions e.g., Hypertension, Diabetes, Heart condition, Pregnancy",
                    ),
                ),
                (
                    "medical_alert_flag",
                    models.BooleanField(
                        default=False,
                        help_text="Flag true if patient has critical high-risk medical alerts",
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="tenants.clinic",
                    ),
                ),
                (
                    "primary_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients",
                        to="tenants.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("clinic", "patient_id")},
            },
        ),
    ]
