# Generated by Django 6.1.1 on 2026-09-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="emergancy_contact_name",
            new_name="emergency_contact_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="emergancy_contact_phone",
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="allergies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medical_conditions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
