# Generated by Django 5.0.14 on 2026-09-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="primary_branch",
            new_name="branch",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="email",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="medical_alert_flag",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="registration_date",
        ),
        migrations.AddField(
            model_name="patient",
            name="first_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="last_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_alerts",
            field=models.TextField(
                blank=True,
                help_text="Critical medical alerts (e.g., High BP, Diabetes, Bleeding disorder).",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="allergies",
            field=models.TextField(
                blank=True,
                help_text="Drug or material allergies (e.g., Penicillin, Latex).",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medical_history",
            field=models.TextField(blank=True, help_text="General medical background."),
        ),
        migrations.AlterField(
            model_name="patient",
            name="patient_id",
            field=models.CharField(
                help_text="Unique patient ID within clinic scope.", max_length=50
            ),
        ),
    ]
