# Generated by Django 6.1.1 on 2026-09-11 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_appointment"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalNote",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subjective",
                    models.TextField(
                        blank=True,
                        help_text="Chief complaint, history of present illness",
                        null=True,
                    ),
                ),
                (
                    "objective",
                    models.TextField(
                        blank=True,
                        help_text="Clinical findings, examination, vitals",
                        null=True,
                    ),
                ),
                (
                    "assessment",
                    models.TextField(
                        blank=True,
                        help_text="Diagnosis & condition evaluation",
                        null=True,
                    ),
                ),
                (
                    "plan",
                    models.TextField(
                        blank=True,
                        help_text="Treatment plan, prescriptions, recommendations",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_note",
                        to="patients.appointment",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.clinic"
                    ),
                ),
                (
                    "dentist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_notes",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DentalRecord",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tooth_number", models.IntegerField(db_index=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("DECAYED", "Decayed (Caries)"),
                            ("FILLED", "Filled"),
                            ("MISSING", "Missing / Extracted"),
                            ("CROWN", "Crown / Bridge"),
                            ("RCT", "Root Canal Treated"),
                            ("IMPLANT", "Dental Implant"),
                        ],
                        default="HEALTHY",
                        max_length=20,
                    ),
                ),
                ("surface_mesial", models.BooleanField(default=False)),
                ("surface_distal", models.BooleanField(default=False)),
                ("surface_occlusal", models.BooleanField(default=False)),
                ("surface_buccal", models.BooleanField(default=False)),
                ("surface_lingual", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.clinic"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dental_records",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "unique_together": {("patient", "tooth_number")},
            },
        ),
    ]
