# Generated by Django 6.1.1 on 2026-09-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_clinicalnote_dentalrecord"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="patient",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("CONFIRMED", "Confirmed"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="SCHEDULED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="clinicalnote",
            name="assessment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clinicalnote",
            name="objective",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clinicalnote",
            name="plan",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clinicalnote",
            name="subjective",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.RemoveField(
            model_name="patient",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="alternate_phone",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="emergency_contact_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="emergency_contact_phone",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="medical_conditions",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="patient_code",
        ),
    ]
