# Generated by Django 5.0.14 on 2026-09-17 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created Record"),
                            ("UPDATE", "Updated Record"),
                            ("DELETE", "Deleted Record"),
                            ("LOGIN", "User Login"),
                            ("LOGOUT", "User Logout"),
                        ],
                        default="CREATE",
                        max_length=20,
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        help_text="e.g., Patient, Charge, Payment, Prescription",
                        max_length=100,
                    ),
                ),
                ("target_object_id", models.CharField(blank=True, max_length=100)),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the modification or event."
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="tenants.branch",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="tenants.clinic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
