# Generated by Django 5.0.14 on 2026-09-16 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("CHECKED_IN", "Checked In (Waiting)"),
                            ("IN_PROGRESS", "In Progress (With Doctor)"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "token_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Live daily queue sequence number.",
                        null=True,
                    ),
                ),
                (
                    "reason_for_visit",
                    models.TextField(
                        blank=True, help_text="Chief complaint or reason for visit."
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal staff or doctor notes."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="tenants.branch",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="tenants.clinic",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["DOCTOR", "CLINIC_ADMIN"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctor_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["appointment_date", "start_time"],
            },
        ),
    ]
