# Generated by Django 5.0.14 on 2026-09-17 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="reason_for_visit",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="token_number",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="appointment",
            name="follow_up_notes",
            field=models.TextField(
                blank=True,
                help_text="Reason or timeline for next appointment (e.g. suture removal in 7 days)",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="next_appointment_required",
            field=models.BooleanField(
                default=False, help_text="Is a follow-up appointment required?"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reason",
            field=models.TextField(
                blank=True, help_text="Chief complaint or purpose of appointment"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctor_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("CONFIRMED", "Confirmed"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("NO_SHOW", "No Show"),
                ],
                default="SCHEDULED",
                max_length=20,
            ),
        ),
    ]
